name: Add Issue to Board

on:
  issues:
    types: [opened]

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Tweets
          column: Ideas
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
          action: add
